USE [master]
GO
/****** Object:  Database [UpMeet]    Script Date: 10/19/2020 4:44:45 PM ******/
CREATE DATABASE [UpMeet]
GO
ALTER DATABASE [UpMeet] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UpMeet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UpMeet] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UpMeet] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UpMeet] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UpMeet] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UpMeet] SET ARITHABORT OFF 
GO
ALTER DATABASE [UpMeet] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UpMeet] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UpMeet] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UpMeet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UpMeet] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UpMeet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UpMeet] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UpMeet] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UpMeet] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UpMeet] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UpMeet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UpMeet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UpMeet] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UpMeet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UpMeet] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UpMeet] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UpMeet] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UpMeet] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UpMeet] SET  MULTI_USER 
GO
ALTER DATABASE [UpMeet] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UpMeet] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UpMeet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UpMeet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UpMeet] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UpMeet] SET QUERY_STORE = OFF
GO
USE [UpMeet]
GO
/****** Object:  Table [dbo].[Events]    Script Date: 10/19/2020 4:44:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[EventID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[Date] [date] NOT NULL,
 CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Favorites]    Script Date: 10/19/2020 4:44:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favorites](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[EventID] [int] NOT NULL,
 CONSTRAINT [PK_Favorites] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Events] ON 
GO
INSERT [dbo].[Events] ([EventID], [Name], [Description], [Date]) VALUES (1, N'Party 1', N'It''s a party', CAST(N'2020-10-31' AS Date))
GO
INSERT [dbo].[Events] ([EventID], [Name], [Description], [Date]) VALUES (2, N'Thanksgiving', N'Turkey time', CAST(N'2020-11-26' AS Date))
GO
SET IDENTITY_INSERT [dbo].[Events] OFF
GO
SET IDENTITY_INSERT [dbo].[Favorites] ON 
GO
INSERT [dbo].[Favorites] ([ID], [Username], [EventID]) VALUES (1, N'testuser', 1)
GO
INSERT [dbo].[Favorites] ([ID], [Username], [EventID]) VALUES (2, N'testuser', 2)
GO
INSERT [dbo].[Favorites] ([ID], [Username], [EventID]) VALUES (3, N'testuser2', 1)
GO
SET IDENTITY_INSERT [dbo].[Favorites] OFF
GO
ALTER TABLE [dbo].[Favorites]  WITH CHECK ADD  CONSTRAINT [FK_Favorites_Events] FOREIGN KEY([EventID])
REFERENCES [dbo].[Events] ([EventID])
GO
ALTER TABLE [dbo].[Favorites] CHECK CONSTRAINT [FK_Favorites_Events]
GO
USE [master]
GO
ALTER DATABASE [UpMeet] SET  READ_WRITE 
GO
